services:
  postgres:
    image: postgres:15
    container_name: biointeraction-postgres
    environment:
      POSTGRES_DB: biointeraction_db
      POSTGRES_USER: bio_user
      POSTGRES_PASSWORD: bio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: biointeraction-neo4j
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7474:7474"
      - "7687:7687"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: biointeraction-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  backend:
    build:
      context: ./backend-java
    container_name: biointeraction-backend
    depends_on:
      - postgres
      - neo4j
      - elasticsearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biointeraction_db
      SPRING_DATASOURCE_USERNAME: bio_user
      SPRING_DATASOURCE_PASSWORD: bio_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
