version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: biointeraction-postgres
    environment:
      POSTGRES_DB: biointeraction_db
      POSTGRES_USER: bio_user
      POSTGRES_PASSWORD: bio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
