spring.application.name=biointeraction-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/biointeraction_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bio_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bio_pass}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.jpa.open-in-view=false
